// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eglsybvrlegoqpvpqmda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnbHN5YnZybGVnb3FwdnBxbWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzE3MjcsImV4cCI6MjA2MDA0NzcyN30.lb7174LgdkcX_gWIAgzJSAxHX6Gy2Gf_xJWWOFLVdic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);